# Generated by Django 3.0.5 on 2020-05-01 13:13

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
        ('accounts', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hp',
            field=models.IntegerField(default=1, verbose_name='current hp'),
        ),
        migrations.AddField(
            model_name='user',
            name='money',
            field=models.IntegerField(default=0, verbose_name='money'),
        ),
        migrations.AddField(
            model_name='user',
            name='st_point',
            field=models.IntegerField(default=0, verbose_name='status point'),
        ),
        migrations.AddField(
            model_name='user',
            name='status_arm',
            field=models.IntegerField(default=1, verbose_name='status arm'),
        ),
        migrations.AddField(
            model_name='user',
            name='status_hp',
            field=models.IntegerField(default=1, verbose_name='status hp'),
        ),
        migrations.AddField(
            model_name='user',
            name='status_luck',
            field=models.IntegerField(default=1, verbose_name='status luck'),
        ),
        migrations.AddField(
            model_name='user',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='equipments.Weapon', verbose_name='武器'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(help_text='Required. 128 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=128, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='password'),
        ),
    ]
