# Generated by Django 3.0.5 on 2020-05-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200501_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hp',
            field=models.IntegerField(default=1, verbose_name='体力'),
        ),
        migrations.AlterField(
            model_name='user',
            name='money',
            field=models.IntegerField(default=0, verbose_name='所持金'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='st_point',
            field=models.IntegerField(default=0, verbose_name='ステータスポイント'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_arm',
            field=models.IntegerField(default=1, verbose_name='腕力'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_hp',
            field=models.IntegerField(default=10, verbose_name='最大体力'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status_luck',
            field=models.IntegerField(default=1, verbose_name='幸運'),
        ),
    ]
