# Generated by Django 3.0.5 on 2020-05-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200504_0102'),
        ('accounts', '0004_auto_20200505_0015'),
    ]

    operations = [
    ]
