# Generated by Django 3.0.5 on 2020-05-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200508_2145'),
        ('accounts', '0005_merge_20200506_1940'),
    ]

    operations = [
    ]
