# Generated by Django 3.0.5 on 2020-05-01 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='weapon name')),
                ('atk', models.IntegerField(default=1, verbose_name='weapon attack')),
                ('price', models.IntegerField(default=0, verbose_name='weapon price')),
                ('required_arm', models.IntegerField(default=1, verbose_name='weapon required arm')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
            ],
        ),
    ]
