# Generated by Django 3.0.5 on 2020-05-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_auto_20200505_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前'),
        ),
    ]
