# Generated by Django 3.0.5 on 2020-05-04 14:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20200504_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnemyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'An enemy with that name already exists.'}, help_text='Required. 100 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=100, unique=True, verbose_name='名前')),
                ('status_hp', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'HP must 1 or more.')], verbose_name='最大体力')),
                ('atk', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Attack point must 1 or more.')], verbose_name='攻撃力')),
                ('reward_money', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Reward money must 1 or more.')], verbose_name='報酬金')),
                ('reward_st_point', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1, 'Reward status point must 1 or more.')], verbose_name='報酬ステータスポイント')),
                ('image', models.ImageField(upload_to='images/', verbose_name='画像')),
                ('enabled', models.BooleanField(default=True, help_text='Designates whether this enemy should be treated as active. Unselect this instead of deleting enemy data.', verbose_name='有効')),
            ],
            options={
                'verbose_name': '敵',
                'verbose_name_plural': '敵',
            },
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(verbose_name='体力')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.EnemyType')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('damage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1, 'Contributed damage must 0 or more.')], verbose_name='貢献ダメージ')),
                ('received', models.BooleanField(default=False, help_text='Designates whether the user got rewards. ', verbose_name='受け取り済み')),
                ('enemy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='battles.Enemy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
            ],
        ),
    ]
