# Generated by Django 3.0.5 on 2020-05-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contribution',
            options={'verbose_name': '貢献度', 'verbose_name_plural': '貢献度'},
        ),
        migrations.AlterModelOptions(
            name='enemy',
            options={'verbose_name': '敵', 'verbose_name_plural': '敵'},
        ),
        migrations.AlterModelOptions(
            name='enemytype',
            options={'verbose_name': '敵の種類', 'verbose_name_plural': '敵の種類'},
        ),
        migrations.AlterField(
            model_name='contribution',
            name='damage',
            field=models.IntegerField(default=0, verbose_name='貢献ダメージ'),
        ),
        migrations.AlterField(
            model_name='enemytype',
            name='atk',
            field=models.IntegerField(default=1, verbose_name='攻撃力'),
        ),
        migrations.AlterField(
            model_name='enemytype',
            name='name',
            field=models.CharField(error_messages={'unique': 'An enemy with that name already exists.'}, help_text='Required. 100 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=100, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='enemytype',
            name='reward_money',
            field=models.IntegerField(default=1, verbose_name='報酬金'),
        ),
        migrations.AlterField(
            model_name='enemytype',
            name='reward_st_point',
            field=models.IntegerField(default=1, verbose_name='報酬ステータスポイント'),
        ),
        migrations.AlterField(
            model_name='enemytype',
            name='status_hp',
            field=models.IntegerField(default=1, verbose_name='最大体力'),
        ),
    ]
