# Generated by Django 3.0.5 on 2020-05-08 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('battles', '0002_auto_20200504_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー'),
        ),
        migrations.AlterField(
            model_name='enemytype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名前'),
        ),
    ]
