# Generated by Django 3.0.5 on 2020-05-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battles', '0003_auto_20200508_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='enemy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='battles.Enemy', verbose_name='敵'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='battles.EnemyType', verbose_name='敵の種類'),
        ),
        migrations.AlterField(
            model_name='enemytype',
            name='image',
            field=models.ImageField(upload_to='battles/enemytypes/images/', verbose_name='画像'),
        ),
    ]
